# Generated by Django 4.0.4 on 2022-06-14 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=30, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=30, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, db_column='UF', max_length=2, null=True, verbose_name='Estado')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, unique=True, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], max_length=1, verbose_name='Estatus')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('dtanasc', models.DateField(blank=True, db_column='dtanasc', null=True, verbose_name='Data de nascimento')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=30, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=30, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, db_column='UF', max_length=2, null=True, verbose_name='Estado')),
                ('celular_whatsapp', models.CharField(max_length=25, unique=True, verbose_name='Celular - WhatsApp')),
                ('celular_recado', models.CharField(blank=True, max_length=25, null=True, verbose_name='Contato Recado')),
                ('estado_civil', models.CharField(choices=[('1', 'Solteiro(a)'), ('2', 'Casado(a)'), ('3', 'Divorciado(a)'), ('4', 'Viuvo(a)'), ('5', 'União Estável'), ('6', 'Outros')], max_length=1, verbose_name='Estado Civil')),
                ('nome_conjuge', models.CharField(max_length=100, verbose_name='Cônjuge')),
                ('naturalidade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Naturalidade')),
                ('nacionalidade', models.CharField(max_length=20, verbose_name='Nacionalidade')),
                ('status', models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], max_length=1, verbose_name='Estatus')),
                ('tipo_usuario', models.CharField(choices=[('1', 'Administrador'), ('2', 'Responsável'), ('3', 'Cuidador'), ('4', 'Dependente'), ('5', 'Técnico em Enfermagem')], max_length=1, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.usuario')),
                ('parentesco_choices', models.CharField(choices=[('1', 'Filho'), ('2', 'Neto'), ('3', 'Irmão'), ('4', 'Outro')], max_length=1, verbose_name='Tipo de Responsável')),
                ('familia', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portal.familia')),
            ],
            bases=('portal.usuario',),
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.usuario')),
                ('convenio_medico', models.CharField(max_length=100, verbose_name='Convênio')),
                ('contato_fone_convenio', models.CharField(max_length=20, verbose_name='Telefone Convênio')),
                ('contato_endereco_convenio', models.CharField(max_length=100, verbose_name='Endereço Convênio')),
                ('familia', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portal.familia')),
            ],
            bases=('portal.usuario',),
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.usuario')),
                ('data_inicio', models.DateField(blank=True, db_column='dtaIni', null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, db_column='dtaFim', null=True, verbose_name='Data da Saída')),
                ('regime_contratacao', models.CharField(choices=[('1', 'CLT'), ('2', 'PJ'), ('3', 'Free Lance'), ('4', 'Prestação Serviços')], max_length=1, verbose_name='Regime de Contratação')),
                ('carga_horaria_semanal', models.IntegerField(blank=True, db_column='carga_horaria_semanal', null=True, verbose_name='Carga Hóraria Semanal')),
                ('turno_trabalho', models.CharField(choices=[('1', 'Diurno'), ('2', 'Noturno')], max_length=1, verbose_name='Turno')),
                ('quem_indicou', models.CharField(max_length=100, verbose_name='Indicação')),
                ('salario_atual', models.DecimalField(db_column='salario_atual', decimal_places=2, default=0, max_digits=10, verbose_name='Salário atual')),
                ('adicional', models.DecimalField(db_column='adicional', decimal_places=2, default=0, max_digits=10, verbose_name='Adicional noturno')),
                ('dia_pagamento', models.DateField(blank=True, db_column='dia_pagamento', null=True, verbose_name='Dia de pagamento')),
                ('observacao', models.TextField(max_length=1000, verbose_name='Senha')),
                ('familia', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portal.familia')),
            ],
            bases=('portal.usuario',),
        ),
    ]
