# Generated by Django 4.0.4 on 2022-06-29 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='c_p_f',
            new_name='cpf',
        ),
    ]
