# Generated by Django 4.0.4 on 2022-06-29 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_rename_c_p_f_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='familia',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='portal.familia', verbose_name='Família'),
        ),
    ]
