# Generated by Django 4.0.4 on 2022-06-29 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_responsavel_familia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuidador',
            name='senha',
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='regime_contratacao',
            field=models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'PJ'), ('FREE', 'Free Lance'), ('PS', 'Prestação Serviços')], max_length=6, verbose_name='Contratação'),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='turno_trabalho',
            field=models.CharField(choices=[('D', 'Diurno'), ('N', 'Noturno')], max_length=1, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='familia',
            field=models.ForeignKey(blank=True, limit_choices_to='1', on_delete=django.db.models.deletion.CASCADE, to='portal.familia'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='parentesco',
            field=models.CharField(choices=[('F', 'Filho'), ('N', 'Neto'), ('I', 'Irmão'), ('O', 'Outro')], max_length=1, verbose_name='Tipo de Responsável'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1, null=True, verbose_name='Estatus'),
        ),
    ]
