# Generated by Django 4.0.4 on 2022-06-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_cuidador_senha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='regime_contratacao',
            field=models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'PJ'), ('FREE', 'Free Lance'), ('PS', 'Prestação Serviços')], max_length=10, verbose_name='Contratação'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('1', 'Solteiro(a)'), ('2', 'Casado(a)'), ('3', 'Divorciado(a)'), ('4', 'Viuvo(a)'), ('5', 'União Estável'), ('6', 'Outros')], max_length=10, null=True, verbose_name='Estado Civil'),
        ),
    ]
