# Generated by Django 4.0.4 on 2022-06-30 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_dependente_contato_endereco_convenio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='familia',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='portal.familia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='celular_whatsapp',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Celular-What'),
        ),
    ]
