# Generated by Django 4.0.4 on 2022-06-30 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_dependente_familia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidador',
            name='senha',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='adicional',
            field=models.DecimalField(blank=True, db_column='adicional', decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Adicional'),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='carga_horaria_semanal',
            field=models.IntegerField(db_column='carga_horaria_semanal', default=44, verbose_name='Carga Hor Sem'),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='dia_pagamento',
            field=models.IntegerField(blank=True, db_column='dia_pagamento', null=True, verbose_name='Dia pag'),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='familia',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='portal.familia'),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='observacao',
            field=models.TextField(max_length=1000, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='regime_contratacao',
            field=models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'PJ'), ('FREE', 'Free Lance'), ('PS', 'Prestação Serviços')], max_length=10, null=True, verbose_name='Contratação'),
        ),
    ]
