# Generated by Django 4.0.5 on 2022-07-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_remove_posconsulta_dependente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posconsulta',
            name='observacao',
            field=models.TextField(blank=True, null=True,
                                   verbose_name='Observação'),
        ),
    ]
