# Generated by Django 4.0.5 on 2022-07-04 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0003_alter_posconsulta_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posconsulta',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='pos_consultas', to='consulta.consulta'),
        ),
    ]
