# Generated by Django 4.0.5 on 2022-07-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_remove_medicamento_pos_consulta'),
        ('consulta', '0004_alter_posconsulta_consulta'),
    ]

    operations = [
    ]
