# Generated by Django 4.0.5 on 2022-07-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(
                blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
