# Generated by Django 4.0.5 on 2022-07-02 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_alter_consulta_dependente_and_more'),
        ('crm', '0002_alter_usuario_options_delete_responsavel_responsavel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dependente',
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('crm.usuario',),
        ),
    ]
